
  name: qtwidgetdemo
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: A simple qt/qml demo # 79 char long summary
  description: |
    A simple QT/QML demo just for fun.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    application:
    # See 'snapcraft plugins'
    plugin: qmake
    project-files: ["qttempwidget.pro"]
    source: .
    build-packages:
      - qtbase5-dev
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
      - qtbase5-dev
      - libmosquitto-dev
      - libmosquittopp-dev
      - mosquitto-dev
      - qml-module-qtquick-extras
      - qtdeclarative5-dev
  
