  name: qtwidgetdemo
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: A simple qt/qml demo # 79 char long summary
  description: |
    A simple QT/QML demo just for fun.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    qtwidgetdemo :
        command: desktop-launch qtwidgetdemo
  
  plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

  parts:
    qt-app:
    source: .
    # See 'snapcraft plugins'
    plugin: qmake
    qt-version: qt5
    source: .
    prime:  
      - -usr/share/doc  
      - -usr/include
      
    after: [desktop-ubuntu-app-platform]
    install: |
      # Create directory to serve as mount point for ubuntu-app-platform
      mkdir $SNAPCRAFT_PART_INSTALL/ubuntu-app-platform 
